### ISSUE TITLE
Add helper functions

### ISSUE THREAD

**Issue by apfohl** [bridgefield/bits#9]
- `SingleOrNothing` (with and w/o predicate)
- `JustNotEmpty`
- `Cast`

**Comment by Dirk-Peters** [comment]
As discussed: SingleOrNothing postponed, since the Exception for multiple entries from Enumerable Extensions needs to be considered. One alternative would introduce Exceptional monads and monad stacks for this function alone.

**Comment by Dirk-Peters** [comment]
JustNotEmpty is intended for strings?
What should Cast do?

**Comment by apfohl** [comment]
`Cast<T>` is `Map<T>` without a function passed.

`JustNotEmpty` can be ignored, as I don't know what it was for.

**Comment by Dirk-Peters** [comment]
I*d like to do Cast<TUp> for Maybe<T> values as up cast when T:TUp because that way it can be  checked by the compiler and we do not get runtime errors we would get for invalid down casts.
This would definitely help with some covariance issue, even though it is not perfect.
However, I don't see a convenient way to do this for now, without an extensions with two generic parameters which will make this not really simple to use.
Maybe there is a way to implement up casts with an implicit conversion operator.

**Comment by apfohl** [comment]
I have no idea at the moment. We can move it to a separate issue.

**Comment by apfohl** [comment]
Resolved with #12
